import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Header from "@/components/Header";
import Page from "@/components/Page";
import { AboutMenuProvider } from "@/contexts/AboutMenuContext";
import APIService from "@/services/APIService";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuList = await APIService.menuList();


  console.log(menuList, "menuList");

  
  return (
    <html lang="en">
      <head>  
      <link href="/assets/css/lib-min.css" rel="stylesheet" />
      <link href="/assets/css/style.css" rel="stylesheet" />
    

      <link rel="icon" href="/assets/images/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AboutMenuProvider>
          <Header menuList={menuList} />
          <Page menuList={menuList} >{children}</Page>
        </AboutMenuProvider>
      </body>
    </html>
  );
}
